name: Deploy to Development
env:
  PIPELINE: Development
on: 
  pull_request:
    branches:
      - main
jobs:
  deploy-to-development-job:
    runs-on: ubunto-latest
    environment:
      name: Development
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: action/setup-dotnet@v2