name: Deploy to Production
env:
  PIPELINE: Production
on: 
  push:
    branches:
      - main
jobs:
  deploy-to-production-job:
    runs-on: ubunto-latest
    environment:
      name: Production
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: action/setup-dotnet@v2

  